---

#--------------------------------------------------
# INSTALLATION FILEBEAT
#--------------------------------------------------
- name: Add Filebeat GPG key to APT
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when:  ansible_os_family == "Debian"

- name: Add FileBeat repo to APT repositories
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
  when: ansible_os_family == "Debian"

- name: Add Docker repo to YUM repositories
  yum_repository:
    file: elastic
    name: elastic-7.x
    description: Elastic repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes
  when: ansible_os_family == "RedHat"

- name: Install Debian OS packages
  apt:
    name: ['apt-transport-https', 'filebeat']
    state: latest
    update_cache: yes
    force: yes
    install_recommends: no
  async: 120
  poll: 10
  when: not ansible_check_mode and ansible_os_family == "Debian"
  ignore_errors: "{{ ansible_check_mode }}"

- name : Install RedHat OS packages
  yum:
    name: ['filebeat']
    update_cache: yes
  async: 120
  poll: 10
  when: not ansible_check_mode and ansible_os_family == "RedHat"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Check installed Debian OS packages
  apt:
    name: ['apt-transport-https', 'filebeat']
    state: latest
    update_cache: yes
    force: yes
    install_recommends: no
  when: ansible_check_mode and ansible_os_family == "Debian"

- name : Check installed RedHat OS packages
  yum:
    name: ['filebeat']
    update_cache: yes
  when: ansible_check_mode and ansible_os_family == "RedHat"

- name: make sure filebeat is enabled
  service: name=filebeat enabled=yes state=started

#--------------------------------------------------
# CONFIGURATION FILEBEAT
#--------------------------------------------------

- name: Push logstash certificate
  copy:
    content: "{{ logstash_tls_crt }}"
    dest: "/etc/ssl/certs/logstash.crt"
    owner: root
    group: root
    mode: '0644'
  notify: restart filebeat

- name: push Filebeat configuration file
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0600'
  notify: restart filebeat

- name: push Filebeat modules configuration file
  copy:
    src: "{{ item }}.yml"
    dest: /etc/filebeat/modules.d/{{ item }}.yml
    owner: root
    group: root
    mode: '0644'
  with_items:
    - iptables
    - system
  notify: restart filebeat

- name: push Filebeat traefik module configuration file
  template:
    src: "{{ item }}.yml.j2"
    dest: /etc/filebeat/modules.d/{{ item }}.yml
    owner: root
    group: root
    mode: '0644'
  with_items:
    - traefik
  when: inventory_hostname in groups.docker
  notify: restart filebeat
