---

- hosts: all
  become: yes
  roles:
  - { role: init_server, tags: init }

- hosts: backup_server
  gather_facts: no
  become: yes
  roles:
  - { role: backup_server_conf, tags: backup }

- hosts: docker
  gather_facts: no
  become: yes
  roles:
  - { role: docker_server, tags: docker }

- hosts: docker_auth
  gather_facts: no
  become: yes
  roles:
  - { role: docker_auth, tags: docker_auth }

- hosts: docker_odoo
  gather_facts: no
  become: yes
  roles:
  - { role: docker_odoo, tags: docker_odoo }

- hosts: docker_nextcloud
  gather_facts: no
  become: yes
  roles:
  - { role: docker_nextcloud, tags: docker_nextcloud }
  - { role: docker_cloudaborative, tags: docker_cloudaborative }

- hosts: docker_owncloud
  gather_facts: no
  become: yes
  roles:
  - { role: docker_owncloud, tags: docker_owncloud }

- hosts: docker_etherpad
  gather_facts: no
  become: yes
  roles:
  - { role: docker_etherpad, tags: docker_etherpad }

- hosts: docker_privatebin
  gather_facts: no
  become: yes
  roles:
  - { role: docker_privatebin, tags: docker_privatebin }

- hosts: docker_framadate
  gather_facts: no
  become: yes
  roles:
  - { role: docker_framadate, tags: docker_framadate }

- hosts: ICCFinance_Pilotage
  gather_facts: no
  become: yes
  roles:
  - { role: mssql_connect, tags: mssql }

- hosts: odoo_server
  gather_facts: no
  become: yes
  roles: 
  - { role: odoo_server, tags: odoo }

- hosts: owncloud_server
  gather_facts: no
  become: yes
  roles:
  - { role: owncloud, tags: owncloud } 

- hosts: all
  gather_facts: no
  become: yes
  roles:
  - { role: iptables, tags: iptables }

- hosts: all 
  gather_facts: no
  become: yes
  roles: 
  - { role: nagios_nrpe, tags: nrpe }

- hosts: nagios_server
  gather_facts: no
  become: yes
  roles:
  - { role: nagios, tags: nagios }

- hosts: docker_nagios
  gather_facts: no
  become: yes
  roles:
  - { role: docker_nagios, tags: docker_nagios }
