---
#--------------------------------------------------
# Install Bank export module
#--------------------------------------------------
- name: Clone Weboob GIT repo
  git: repo="https://git.weboob.org/weboob/weboob.git" version="master" dest="/root/weboob"
  register: weboob

- name: Install necessary python modules
  pip:
    name:
      [
        "prettytable",
        "cssselect",
        "html2text",
        "unidecode",
        "pbr",
        "python-swiftclient",
        "python-keystoneclient",
      ]

- name: Create Config directory
  file:
    name: /root/.config/weboob
    state: directory

- name: Copy configuration file
  template: src=backends.j2 dest=/root/.config/weboob/backends mode=0400

- name: Create OFX directory
  file:
    name: /ofx
    state: directory
    owner: "{{ odoo_user }}"
    group: "{{ odoo_user }}"

- name: add cron job to get bank account every day
  cron:
    name: import bank moves
    minute: 30
    hour: 20
    job: /root/weboob/tools/local_run.sh boobank history {{ bank_account }} `date -d "last week" +\%Y-\%m-\%d` -f ofx | sed -n '/OFXHEADER/,$p' | sed 's/.*OFXHEADER/OFXHEADER/g' | sed 's/ACCTID>CPT/ACCTID>/g' > /ofx/bank_account_import.ofx ; chmod 444 /ofx/bank_account_import.ofx

- name: add cron job to get bank account 2 every day
  cron:
    name: import bank moves account 2
    minute: 50
    hour: 20
    job: /root/weboob/tools/local_run.sh boobank history {{ bank_account2 }} `date -d "last week" +\%Y-\%m-\%d` -f ofx | sed -n '/OFXHEADER/,$p' | sed 's/.*OFXHEADER/OFXHEADER/g' | sed 's/ACCTID>CPT/ACCTID>/g' > /ofx/bank_account2_import.ofx ; chmod 444 /ofx/bank_account2_import.ofx
  when: bank_account2 is defined

- name: add cron job to get bank account 3 every day
  cron:
    name: import bank moves account 3
    minute: 10
    hour: 21
    job: /root/weboob/tools/local_run.sh boobank history {{ bank_account3 }} `date -d "last week" +\%Y-\%m-\%d` -f ofx | sed -n '/OFXHEADER/,$p' | sed 's/.*OFXHEADER/OFXHEADER/g' | sed 's/ACCTID>CPT/ACCTID>/g' > /ofx/bank_account3_import.ofx ; chmod 444 /ofx/bank_account3_import.ofx
  when: bank_account3 is defined

- name: add cron job to get bank 2 account every day
  cron:
    name: import bank 2 moves
    minute: 25
    hour: 20
    job: /root/weboob/tools/local_run.sh boobank history {{ bank2_account }} `date -d "last week" +\%Y-\%m-\%d` -f ofx | sed -n '/OFXHEADER/,$p' | sed 's/.*OFXHEADER/OFXHEADER/g' | sed 's/ACCTID>CPT/ACCTID>/g' > /ofx/bank2_account_import.ofx ; chmod 444 /ofx/bank2_account_import.ofx
  when: bank2_account is defined

- name: add cron job to get bank 2 account 2 every day
  cron:
    name: import bank 2 moves account 2
    minute: 45
    hour: 20
    job: /root/weboob/tools/local_run.sh boobank history {{ bank2_account2 }} `date -d "last week" +\%Y-\%m-\%d` -f ofx | sed -n '/OFXHEADER/,$p' | sed 's/.*OFXHEADER/OFXHEADER/g' > /ofx/bank2_account2_import.ofx ; chmod 444 /ofx/bank2_account2_import.ofx
  when: bank2_account2 is defined
