---
#--------------------------------------------------
# System Settings
#--------------------------------------------------
- name: Create odoo system group
  group:
    name: "{{ odoo_user }}"
    system: yes
  tags: preinstall

- name: Create ODOO system user
  user:
    system: yes
    name: "{{ odoo_user }}"
    group: "{{ odoo_user }}"
  tags: preinstall

- name: Create Log directory
  file:
    name: /var/log/{{ odoo_user }}
    state: directory
    owner: "{{ odoo_user }}"
    group: "{{ odoo_user }}"
  tags: preinstall

- name: Install tool packages relase <= 18.04
  apt:
    name:
      [
        "wget",
        "git",
        "bzr",
        "bzrtools",
        "python-pip",
        "postgresql",
        "postgresql-server-dev-all",
        "python-all-dev",
        "python-dev",
        "python-pil",
        "python-setuptools",
        "libxml2-dev",
        "libxslt1-dev",
        "libevent-dev",
        "libsasl2-dev",
        "libldap2-dev",
        "libffi-dev",
        "pkg-config",
        "libtiff5-dev",
        "libjpeg8-dev",
        "libjpeg-dev",
        "zlib1g-dev",
        "libfreetype6-dev",
        "liblcms2-dev",
        "liblcms2-utils",
        "libwebp-dev",
        "tcl8.6-dev",
        "tk8.6-dev",
        "python-tk",
        "libyaml-dev",
        "fontconfig",
        "node-less",
        "nodejs",
        "duplicity",
      ]
    force: yes
    install_recommends: no
  tags: preinstall
  when: ansible_distribution_release <= "18.04"

- name: Install tool packages relase > 18.04
  apt:
    name:
      [
        "wget",
        "git",
        "bzr",
        "bzrtools",
        "python3-pip",
        "postgresql",
        "postgresql-client",
        "postgresql-contrib",
        "python3-psycopg2",
        "python-all-dev",
        "python-dev",
        "python-pil",
        "python-setuptools",
        "libxml2-dev",
        "libxslt1-dev",
        "libevent-dev",
        "libsasl2-dev",
        "libldap2-dev",
        "libffi-dev",
        "pkg-config",
        "libtiff5-dev",
        "libjpeg8-dev",
        "libjpeg-dev",
        "zlib1g-dev",
        "libfreetype6-dev",
        "liblcms2-dev",
        "liblcms2-utils",
        "libwebp-dev",
        "tcl8.6-dev",
        "tk8.6-dev",
        "python-tk",
        "libyaml-dev",
        "fontconfig",
        "node-less",
        "nodejs",
        "duplicity",
        "build-essential",
        "python3-dev",
        "python3-venv",
        "python3-wheel",
        "libxslt-dev",
        "libzip-dev",
        "libldap2-dev",
        "libsasl2-dev",
        "python3-setuptools",
        "gdebi",
        "libpq-dev",
        "python-dev",
      ]
    force: yes
    install_recommends: no
    state: present
  tags: preinstall
  notify: restart postgresql
  when: ansible_distribution_release > "18.04"

- name: Install wkhtmltox
  apt: deb="https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.{{ ansible_distribution_release }}_amd64.deb"
  tags: preinstall

- name: Install npm package
  apt: name="npm" install_recommends=no
  tags: preinstall

- name: Install less
  npm: global="yes" name="less"
  tags: preinstall

- name: Install less-plugin-clean-css
  npm: global="yes" name="less-plugin-clean-css"
  tags: preinstall
