---

- name: Update repo and upgrade installed packages
  apt:
    update_cache: yes
    upgrade: full
    autoremove: yes
    force: yes
    install_recommends: no
  when: ansible_os_family == "Debian"

- name: Remove unecessary Samba packages
  apt:
    name: samba*
    autoremove: yes
    state: absent
  when: ansible_os_family == "Debian"

- name: Remove potentially harmfull unattended-upgrades
  apt:
    name: unattended-upgrades
    autoremove: yes
    state: absent
  when: ansible_distribution == "Ubuntu"

- name: Remove unecessary samba hooks
  file:
    name: /etc/dhcp/dhclient-enter-hooks.d/samba
    state: absent
  when:  ansible_os_family == "Debian"

- name: Update repo and upgrade installed packages
  yum:
    update_cache: yes
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Create {{ host_user }} group
  group:
    name: "{{ host_user }}"

- name: Create {{ host_user }} user
  user:
    name: "{{ host_user }}"
    group: "{{ host_user }}"
    password: "{{ host_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: ed25519
    shell: /bin/bash
  register: publickey

- name: Save public key to hostvars for SFTP
  local_action:
    module: lineinfile
    name: "host_vars/{{ inventory_hostname }}"
    regexp: "host_user_public_key:"
    line: "host_user_public_key: {{ publickey.ssh_public_key }}"
  connection: local
  become: no
  when: initial_playbook is not defined

- name: add user in sudoers
  lineinfile:
    name: /etc/sudoers
    regexp: "^{{ host_user }}"
    line: "{{ host_user }} ALL=(ALL) ALL"

- name: add public key to authorized keys
  authorized_key:
    key: "{{ depl_ssh_pubkey }}"
    user: "{{ host_user }}"
    exclusive: yes
  tags: sshd

- name: configure sshd port
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: "^#?Port"
    line: "Port {{ default_sshd_port }}"
  notify: restart-sshd
  tags: sshd

- name: support for ed25519 keys
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: "^#?HostKey /etc/ssh/ssh_host_ed25519_key"
    line: "HostKey /etc/ssh/ssh_host_ed25519_key"
  notify: restart-sshd
  tags: sshd

- name: fallback support for rsa keys
  lineinfile:
    name: /etc/ssh/sshd_config
    insertafter: "^#?HostKey /etc/ssh/ssh_host_ed25519_key"
    line: "HostKey /etc/ssh/ssh_host_rsa_key"
  notify: restart-sshd
  when: inventory_hostname in groups.backup_server
  tags: sshd

- name: Kex Algorithms
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: "^#?KexAlgorithms "
    insertafter: "^# Ciphers and keying"
    line: "KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256"
  notify: restart-sshd
  tags: sshd

- name: Ciphers
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: "^#?Ciphers "
    insertafter: "^KexAlgorithms"
    line: "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
  notify: restart-sshd
  tags: sshd

- name: MACs
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: "^#?MACs "
    insertafter: "^Cipher"
    line: "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
  notify: restart-sshd
  tags: sshd

- name: Verbose Log Level
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: "^#?LogLevel "
    line: "LogLevel VERBOSE"
  notify: restart-sshd
  tags: sshd

- name: Authentication Methods
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: "^#?AuthenticationMethods "
    insertafter: "^# Authentication:"
    line: "AuthenticationMethods publickey"
  notify: restart-sshd
  tags: sshd

- name: Disable ssh root login
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
  notify: restart-sshd
  tags: sshd

- name: Disable access with password, use key only
  lineinfile: 
    name: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: restart-sshd
  tags: sshd

- name: Disable Agent Forwarding
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: "^#?AllowAgentForwarding"
    line: "AllowAgentForwarding no"
  notify: restart-sshd
  tags: sshd

- name: Disable TCP Forwarding
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: "^#?AllowTcpForwarding"
    line: "AllowTcpForwarding no"
  notify: restart-sshd
  tags: sshd

- name: Disable X11 Forwarding
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: "^#?X11Forwarding"
    line: "X11Forwarding no"
  notify: restart-sshd
  tags: sshd

- name: Add support for SFTP and logging
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: "^#?Subsystem.*sftp"
    line: "Subsystem sftp /usr/lib/openssh/sftp-server -f AUTHPRIV -l INFO"
  notify: restart-sshd
  tags: sshd

- name: Enable ssh connection for {{ host_user }} only
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: "^#?AllowUsers"
    line: "AllowUsers {{ host_user }}"
  when: inventory_hostname not in groups.backup_server
  notify: restart-sshd
  tags: sshd

- name: Enable ssh connection for {{ host_user }} and SFTP users on Backup server
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      AllowUsers {{ host_user }} {{ (groups.servers | difference(groups.backup_server)) | map('extract', hostvars, ['backup_sftp_user']) | sort | join(" ") }}
      AllowGroups {{ host_user }} sftpgroup

      Match Group sftpgroup
              ChrootDirectory /mnt/vdb/backup/sftp
              ForceCommand internal-sftp
              AllowTcpForwarding no
              GatewayPorts no
              X11Forwarding no
  when: inventory_hostname in groups.backup_server
  notify: restart-sshd
  tags: sshd

- name: Add session timeout
  blockinfile:
    path: /etc/bash.bashrc
    block: |
      TMOUT=900
      readonly TMOUT
      export TMOUT
  when: ansible_os_family == "Debian"

- name: Add session timeout
  blockinfile:
    path: /etc/bashrc
    block: |
      TMOUT=900
      readonly TMOUT
      export TMOUT
  when: ansible_os_family == "RedHat"

- name: Copy Installed Package Listing script on server
  template:
    src: collect_installed_packages_facts_{{ ansible_os_family }}.sh.j2
    dest: /root/collect_installed_packages_facts.sh
    owner: root
    group: root
    mode: 0700

- name: add cron job to check installed packages every day
  cron:
    name: collect installed packages facts
    minute: 43
    hour: 0
    job: /root/collect_installed_packages_facts.sh
