---
- name: rebuild auth docker
  docker_service:
    project_src: /home/docker/auth
    build: yes
    recreate: always
    restarted: yes
    remove_orphans: yes
  async: 600
  poll: 10
  when: not ansible_check_mode

- name: start auth docker
  docker_service:
    project_src: /home/docker/auth
    remove_orphans: yes

