---
- name: Create docker auth repo
  file:
    name: /home/docker/auth/sso
    state: directory
    owner: root
    group: root

## Install Auth docker
- name: Install Auth docker architecture
  template:
    src: docker-compose.yaml.j2
    dest: /home/docker/auth/docker-compose.yaml
    owner: root
    group: root
    mode: 0400
  notify: start auth docker

## Backup Auth section
- name: Install auth backup compose file
  template:
    src: backup.yaml.j2
    dest: /home/docker/backups/backup-auth.yaml
    owner: root
    group: root
    mode: 0400
  when: inventory_hostname in groups['maintenance_contract']

- name: Copy docker file for postgres duplicity
  copy:
    src: ../docker_odoo/files/Dockerfile-backup
    dest: /home/docker/backups/Dockerfile-postgres
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname in groups['maintenance_contract']

- name: add cron job to run data backup every day
  cron:
    name: backup auth data
    minute: 03
    hour: 22
    job: /usr/bin/docker exec openldap slapcat -v > /home/docker/backups/ldap_backup.ldif ; chmod 400 /home/docker/backups/ldap_backup.ldif
  when: inventory_hostname in groups['maintenance_contract']

- name: add cron job to run backup every day
  cron:
    name: push auth backup to openstack
    minute: 33
    hour: 22
    job: /usr/local/bin/docker-compose -f /home/docker/backups/backup-auth.yaml run --rm backup_auth
  when: inventory_hostname in groups['maintenance_contract']
