---

- name: Set trusted domain to nextcloud for collaborative documents
  shell: docker exec -u www-data nextcloud php occ --no-warnings "config:system:set" trusted_domains 2 --value="nextcloud"
  when: cloud_onlyoffice is defined

- name: Install OnlyOffice app
  shell: docker exec -u www-data nextcloud php occ --no-warnings "app:enable" onlyoffice
  when: cloud_onlyoffice is defined

- name: Set OnlyOffice URL
  shell: docker exec -u www-data nextcloud php occ --no-warnings "config:system:set" onlyoffice DocumentServerUrl --value="https://{{ cloud_onlyoffice_url}}"
  when: cloud_onlyoffice is defined

- name: Set internal OnlyOffice URL
  shell: docker exec -u www-data nextcloud php occ --no-warnings "config:system:set" onlyoffice DocumentServerInternalUrl --value="http://onlyoffice/"
  when: cloud_onlyoffice is defined

- name: Set internal NextCloud URL
  shell: docker exec -u www-data nextcloud php occ --no-warnings "config:system:set" onlyoffice StorageUrl --value="http://nextcloud/"
  when: cloud_onlyoffice is defined

- name: Set trusted domain to collabora for collaborative documents
  shell: docker exec -u www-data nextcloud php occ --no-warnings "config:system:set" trusted_domains 3 --value="{{ cloud_collabora_url }}"
  when: cloud_collabora is defined

- name: Install Collabora app
  shell: docker exec -u www-data nextcloud php occ --no-warnings "app:enable" richdocuments
  when: cloud_collabora is defined

- name: Set Collabora URL
  shell: docker exec -u www-data nextcloud php occ --no-warnings "config:system:set" richdocuments wopi_url --value="https://{{ cloud_collabora_url}}"
  when: cloud_collabora is defined
