---
- name: pull odoo docker image
  docker_image:
    name: remifilament/odoo:10.0
  tags: rebuild_pull_test

- name: rebuild odoo docker test
  docker_service:
    project_src: /home/docker/odootest/
    build: yes
    nocache: yes
    recreate: always
    restarted: yes
    remove_orphans: yes
  async: 600
  poll: 10
  when: not ansible_check_mode
  tags: rebuild_pull_test, rebuild_test

- name: restart odoo docker test
  docker_service:
    project_src: /home/docker/odootest/
    remove_orphans: yes
    restarted: yes
  tags: restart_test

- name: restart odoo docker whitelists
  docker_service:
    project_src: /home/docker
    files: whitelists.yaml
    project_name: whitelists
    restarted: yes
  tags: restart_whitelists

- name: restart odoo docker prod
  docker_service:
    project_src: /home/docker/odoo/
    remove_orphans: yes
    restarted: yes
  tags: restart_prod

