---
- name: Converge
  hosts: all
  tasks:
    - name: "Include role to prepare the server"
      include_role:
        name: roles/raw_server

    - name: "Include ansible_role_docker_server"
      include_role:
        name: roles/ansible_role_docker_server
