---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Ubuntu
    image: ubuntu:20.04
    groups:
      - docker_nagios
      - docker_auth
      - docker_odoo
provisioner:
  name: ansible
verifier:
  name: ansible
