---

- name: Create SFTP group
  group:
    name: sftpgroup

- name: Create SFTP users
  user:
    name: "{{ hostvars[item].backup_sftp_user }}"
    group: sftpgroup
    password: "!"
    shell: /sbin/nologin
  with_items: "{{ groups.servers | difference(groups.backup_server)}}"

- name: add SFTP users public key to authorized keys
  authorized_key:
    key: "{{ hostvars[item].host_user_public_key }}"
    user: "{{ hostvars[item].backup_sftp_user }}"
    exclusive: yes
  with_items: "{{ groups.servers | difference(groups.backup_server) }}"

- name: Copy sshd_config file
  template:
    src: ../init_server/templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: restart-sshd
  tags: sshd

- name: add pip package
  apt:
    name: ['python3-pip', 'python3-dev', 'python3-setuptools', 'python3-wheel']
    force: yes
    install_recommends: no

- name: check that chroot directory for SFTP users exist
  file:
    name: /backup/sftp
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: check that directories for SFTP for all servers exist
  file:
    name: /backup/sftp/{{ hostvars[item].inventory_hostname | lower }}
    state: directory
    owner: "{{  hostvars[item].backup_sftp_user }}"
    group: sftpgroup
    mode: '0755'
  with_items: "{{ groups.servers | difference(groups.backup_server) }}"

- name: check that directory for collecting openstack Cloud facts exists
  file:
    name: /backup/cloud
    state: directory
    owner: lefilament
    group: lefilament
    mode: '0755'

- name: check that directory for collecting openstack Odoo facts exists
  file:
    name: /backup/odoo
    state: directory
    owner: lefilament
    group: lefilament
    mode: '0755'

- name: check that directory for collecting os/packages/docker facts exists
  file:
    name: /backup/versions
    state: directory
    owner: lefilament
    group: lefilament
    mode: '0755'

- name: install swift client
  pip:
    name: ['python-swiftclient', 'python-keystoneclient']

- name: Copy OpenStack Cloud Fact Collection script on server
  template:
    src: retrieve_openstack_cloud_facts.sh.j2
    dest: /root/retrieve_openstack_cloud_facts.sh
    owner: root
    group: root
    mode: '0700'

- name: add cron job to check OpenStack Cloud content every day
  cron:
    name: check openstack cloud facts
    minute: "43"
    hour: "6"
    job: /root/retrieve_openstack_cloud_facts.sh

- name: Copy OpenStack Odoo Fact Collection script on server
  template:
    src: retrieve_openstack_odoo_facts.sh.j2
    dest: /root/retrieve_openstack_odoo_facts.sh
    owner: root
    group: root
    mode: '0700'

- name: add cron job to check OpenStack Cloud content every day
  cron:
    name: check openstack odoo facts
    minute: "13"
    hour: "6"
    job: /root/retrieve_openstack_odoo_facts.sh

- name: Move versioned files from SFTP directory to versions
  template:
    src: move_versioned_files.sh.j2
    dest: /root/move_versioned_files.sh
    owner: root
    group: root
    mode: '0700'

- name: add cron job to move versioned files from SFTP directory to versions
  cron:
    name: move versioned files
    minute: "43"
    hour: "3"
    job: /root/move_versioned_files.sh
