---

- name: Install dependent packages.
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    install_recommends: no
  with_items:
    - [gnupg2, python3, python3-apt, python3-simplejson, aptitude]
  when: ansible_os_family == "Debian"

# TODO do the same with the redhat family
- name: Initial packages update using raw module
  raw: yum update -y
  tags: raw-redhat
  when: ansible_os_family == "redhat"

- name: Initial packages upgrade using raw module
  raw: yum upgrade -y
  tags: raw-redhat
  when: ansible_os_family == "redhat"

- name: Initial python installation using raw module
  raw: yum install -y libselinux-python3 python3 python3-simplejson aptitude
  tags: raw-redhat
  when: ansible_os_family == "redhat"

